### ISSUE TITLE
Option to skip insert for InsertUpdate (update only)

### ISSUE THREAD

**Issue by herbdool** [wizaplace/php-etl#102]
Thank you for forking this and continuing the work!

Wondering if it would be possible to have an option for InsertUpdate to only do an update? That is, if the item isn't in the table then do *not* insert?

We've got one ETL that populates the table from an API service. But then another API service reports which items were deleted (but only the index). If for some reason an item was deleted before it was extracted then it wouldn't exist in our table. In this case we don't want it to try to insert it, just skip. Is this possible?

**Comment by ecourtial** [comment]
I just looked at the documentation and the code (as mentioned in a other issue, I am not very familiar with this part of the library).
If I understand properly, so far the _InsertUpdate_ component allows:

- To perform Inserts and Updates (default behavior).
- To perform only Inserts (if the _DoUpdates_ param is set to _false_).

So you would like to add another option, allowing to only perform updates right ?

**Comment by herbdool** [comment]
That is correct. I guess that could be `DoInserts` with a default of `true`.

**Comment by ecourtial** [comment]
Allright. 
I am going to have a look a it today with the teammates and if it is ok (I don't see why it wouldn't) I will create a PR so you could try it before merging into master.

**Comment by ecourtial** [comment]
@herbdool I created a PR. Could you test this branch on your side to see if meets your requirements ?

**Comment by herbdool** [comment]
@ecourtial I tested and it works. Though I put a note in the review. Do you think a simple `Update` loader class would be more straightforward? I was debating with myself on this. Wouldn't need any additional flags. That's basically what I was trying to do anyway: just update, no insert.

**Comment by ecourtial** [comment]
@herbdool Please see the new PR #104 and tell me what you think about it (and if it works on your side).

**Comment by herbdool** [comment]
I've tested #104 and it works for me. It updates an existing item and doesn't complain if the item is missing. So that all looks good to me.

**Comment by ecourtial** [comment]
Merged and in tag in 2.1.
