### ISSUE TITLE
Adding a multiline CSV extractor

### ISSUE THREAD

**Issue by ecourtial** [wizaplace/php-etl#3]
The current CSV extractor seems to not work with files with entries which are not in only one line (multiline entries).

Need documentation update.

**Comment by AurelienRasselet** [comment]
Not sure if it's necessary to do a new CSV extractor, it's just a small fix. We could do it for the basic CSV extractor

**Comment by ecourtial** [comment]
@AurelienRasselet OK!

**Comment by ecourtial** [comment]
Fix done and merged.
