### ISSUE TITLE
Is it possible to transform a json that has more than one depth?

### ISSUE THREAD

**Issue by Orann** [wizaplace/php-etl#67]
Hello everyone,

I just found out about your php etl library and I was wondering if it's possible to use `RenameColumns()` from transform for renaming column on a json source that has more than one depth ?

For exemple, following this json file;
```
[
  {
    "id": "110",
    "person": [
      {
        "idPerson": "89",
        "addresses": {
          "home": [
                {
                  "name": "10 rue des châtaigniers",
                  "country": "France"
                }
            ],
         "work": [
                {
                  "name": "12 rue des bois",
                  "country": "Belgium"
                }
            ]
        }
      }
    ]
  }
]
```
I want to load only the id, the idPerson and just the country of the "home" address that corresponding to my database:
```
$etl->extract($extractor, 'fakeDataSource/personAddress.json')
			->transform($transform, ['columns' => ???) //What dit I need to put here?
			->load($loader, 'schema.mytable', ['key' => ['id'], 'columns' => ['id' => 'id', 'id_personne' => 'idPerson', 'pays' => 'country']])
			->run();
```
Thanks in advance for your response, and I'm sorry if I'm in the wrong place to ask this kind of question, so don't hesitate to tell me.

And thank you for this library, it could really save me time on my work, good job ! :smiley:

**Comment by Orann** [comment]
I finally find a way of doing what I wanted, so I share it here if someone have a similar question.

According to the documentation and from what I understood, "For more control over the columns, you may use JSON path", but it have to be done on the extract part. so the whole code should look like this;

```
$connexionFactory = new ConnectionFactory();
$manager = new Manager($connexionFactory);
$manager->addConnection($config);
$etl = new Etl();
$extractor = new Json();
$transform = new RenameColumns();
$loader = new InsertUpdate($manager);

$etl->extract($extractor, 'fakeDataSource/personAddress.json', [
	'columns' => [
		'id' => '$..[id]',
		'idPerson' => '$..[idPerson][*].idPerson',
                'country' => '$..[idPerson][*].addresses[:1].country',
	]
    ])
    ->transform($transform, ['columns' => ['id' => 'id', 'idPerson' => 'id_personne', 'pays' => 'country']])
    ->load($loader, 'schema.mytable', ['key' => ['id']])
    ->run();
```

I'm really not sure if it's the best way of doing it. So it's why I don't close this issue from now.

Don't hesitate to give me feedback or close this issue ! :smiley:

**Comment by ecourtial** [comment]
Well that's a good way to proceed. I don't know if I could have done it differently 👍
