### ISSUE TITLE
Allow multi-line CSV header

### ISSUE THREAD

**Issue by jnbeaver** [wizaplace/php-etl#82]
I came across a bug where the CSV extractor assumes the header is a single line (it uses `fgets` when parsing the header). 

Using the following CSV file:
```
Column 1,Column 2,"Multi-Line
Column 3"
Value 1,Value 2,Value 3
```

Running the following code:
```php
(new Etl())
    ->extract(new Csv(), __DIR__.'/test.csv')
    ->load($loader, '', ['index' => 'Column 1'])
    ->run();
```

I get the following notice when the extractor tries to parse the first row (which is actually the second line of the header):
```
Notice: Undefined offset: 1
```

Thanks for the hard work on this library. I'm happy to make a pull request if you're open to that.

**Comment by Nicolas-Masson-Wizaplace** [comment]
@jnbeaver I did a quick fix, but sure if you see any ehancement or bug fix in the future, we are open to pull requests :)

**Comment by jnbeaver** [comment]
Sounds good, thanks!
