### ISSUE TITLE
Create a CSV splitter

### ISSUE THREAD

**Issue by ecourtial** [wizaplace/php-etl#9]
Create two CSV splitter class.
One splitting the CSV in n parts.
One splitting the CSV in n max lines.

Be careful with the multilines CSV.

Need documentation update.

**Comment by Nicolas-Masson-Wizaplace** [comment]
Splitting in N parts is not really ETL friendly, how can we tell how much lines will be generated before starting Loading ?
Splitting according to max lines is already possible with the current CsvLoader :)

**Comment by ecourtial** [comment]
This ticket is outdated. The request was created while working on the first version of the fork.
