### ISSUE TITLE
Aggregator columns messed up

### ISSUE THREAD

**Issue by Napster33-Supplied** [wizaplace/php-etl#91]
Has anyone encountered this problem when there is no match between two sources that the resulting csv file has the columns messed up?
PS: Data is extracted and aggregated from 2 queries, not csv files and here are the two data sources:
1.
"id";"cId"
3260311;5
3260312;4
3260313;3
2.
"id";"email"
3260312;"test@test.com";
3260315;"test2@test.com";

Thx.

**Comment by Nicolas-Masson-Wizaplace** [comment]
Hello @Napster33-Supplied, i think you need to discard incomplete rows, what about using the `Aggregator::DISCARD` aggregator options (https://github.com/wizaplace/php-etl/blob/e826a7d22411e3ee5a8011447c7906890d1c3f47/docs/Extractors/Aggregator.md#L100-L110)?

**Comment by Napster33-Supplied** [comment]
Hi @Nicolas-Masson-Wizaplace , thanks for your reply, I did try that but with no success. The needed result from my example should be :  
id                       cId        email
3260311             5
3260312             4          test@test.com
3260313             3
3260315                         test2@test.com

**Comment by Nicolas-Masson-Wizaplace** [comment]
Ah ok, got it,

**Comment by Nicolas-Masson-Wizaplace** [comment]
@Napster33-Supplied  Ok got it, did a PR that would fix this behavior.
