### ISSUE TITLE
Is it possible to extract a xml that has more than one loop?

### ISSUE THREAD

**Issue by thangasujithas** [wizaplace/php-etl#94]
I am using the xml that has more than one depth. For example
```
<users>
<user>
<profile>
</profile>
<addresses>
<address></addresses>
</addresses>
</user>
</users>
```
I need to get profile details and address details for each user. How can I extract ? Could anyone give the solution to solve this?

**Comment by ecourtial** [comment]
Hi @thangasujithas 
Never tried. What do you get for the _addresses_ field ?
